import { create } from 'ionicons/icons';

export const categories = [
  {
    id: 1,
    text: 'Service des routes et mobilité',
    value: 'service_des_routes_et_mobilite',
    description:
      "Responsable de l'entretien des routes et de la gestion des transports.",
    contactEmail: 'routes.mobilite@city.ch',
    phoneNumber: '+41 22 123 45 67',
    uniqueCode: 'CH-SRM-001',
  },
  {
    id: 2,
    text: "Service de l'éclairage public",
    value: 'service_de_leclairage_public',
    description:
      "Gère l'éclairage public et assure que les rues sont bien éclairées.",
    contactEmail: 'eclairage.public@city.ch',
    phoneNumber: '+41 22 234 56 78',
    uniqueCode: 'CH-SEP-002',
  },
  {
    id: 3,
    text: 'Service des eaux',
    value: 'service_des_eaux',
    description:
      "Assure l'approvisionnement en eau potable et maintient les infrastructures d'eau.",
    contactEmail: 'eaux@city.ch',
    phoneNumber: '+41 22 345 67 89',
    uniqueCode: 'CH-SDE-003',
    created: false,
  },
  {
    id: 4,
    text: 'Service de la propreté',
    value: 'service_de_la_proprete',
    description: 'Maintient la propreté des espaces publics.',
    contactEmail: 'proprete@city.ch',
    phoneNumber: '+41 22 456 78 90',
    uniqueCode: 'CH-SDP-004',
    created: false,
  },
  {
    id: 5,
    text: 'Service des espaces verts',
    value: 'service_des_espaces_verts',
    description: "Responsable de l'entretien des parcs et des espaces verts.",
    contactEmail: 'espaces.verts@city.ch',
    phoneNumber: '+41 22 567 89 01',
    uniqueCode: 'CH-SEV-005',
    created: false,
  },
  {
    id: 6,
    text: 'Police municipale',
    value: 'police_municipale',
    description:
      "Département de police local assurant la sécurité et l'ordre public.",
    contactEmail: 'police.municipale@city.ch',
    phoneNumber: '+41 22 678 90 12',
    uniqueCode: 'CH-PM-006',
    created: false,
  },
  {
    id: 7,
    text: 'Service de la mobilité',
    value: 'service_de_la_mobilite',
    description: 'Gère la mobilité urbaine et les transports publics.',
    contactEmail: 'mobilite@city.ch',
    phoneNumber: '+41 22 789 01 23',
    uniqueCode: 'CH-SDM-007',
    created: false,
  },
  {
    id: 8,
    text: 'Police cantonale',
    value: 'police_cantonale',
    description: 'Police responsable de la sécurité au niveau cantonal.',
    contactEmail: 'police.cantonale@city.ch',
    phoneNumber: '+41 22 890 12 34',
    uniqueCode: 'CH-PC-008',
    created: false,
  },
  {
    id: 9,
    text: 'Service clientèle Migros',
    value: 'service_clientele_migros',
    description: "Service de soutien et d'assistance aux clients de Migros.",
    contactEmail: 'clientele.migros@migros.ch',
    phoneNumber: '+41 22 901 23 45',
    uniqueCode: 'CH-SCM-009',
    created: false,
  },
  {
    id: 10,
    text: 'Services de secours (144)',
    value: 'services_de_secours_144',
    description: "Services d'urgence pour les secours médicaux.",
    contactEmail: 'secours.144@city.ch',
    phoneNumber: '+41 22 012 34 56',
    uniqueCode: 'CH-SDS-010',
    created: false,
  },
  {
    id: 11,
    text: "Service d'incendie et de secours (SIS)",
    value: 'service_d_incendie_et_de_secours_sis',
    description:
      "Interventions en cas d'incendie et autres situations d'urgence.",
    contactEmail: 'incendie.secours@city.ch',
    phoneNumber: '+41 22 123 45 67',
    uniqueCode: 'CH-SIS-011',
    created: false,
  },
  {
    id: 12,
    text: 'Service vétérinaire cantonal',
    value: 'service_veterinaire_cantonal',
    description:
      'Supervise la santé et le bien-être des animaux au niveau cantonal.',
    contactEmail: 'veterinaire.cantonal@city.ch',
    phoneNumber: '+41 22 234 56 78',
    uniqueCode: 'CH-SVC-012',
    created: false,
  },
  {
    id: 13,
    text: 'Service social',
    value: 'service_social',
    description: "Fournit des services de soutien et d'assistance sociale.",
    contactEmail: 'social@city.ch',
    phoneNumber: '+41 22 345 67 89',
    uniqueCode: 'CH-SS-013',
    created: false,
  },
  {
    id: 14,
    text: 'Service des travaux publics',
    value: 'service_des_travaux_publics',
    description: 'Gère les infrastructures et les travaux publics.',
    contactEmail: 'travaux.publics@city.ch',
    phoneNumber: '+41 22 456 78 90',
    uniqueCode: 'CH-STP-014',
    created: false,
  },
  {
    id: 15,
    text: 'Transport public de Genève',
    value: 'transport_public_de_geneve',
    description: 'Gère les transports publics de Genève.',
    contactEmail: 'transport.geneve@city.ch',
    phoneNumber: '+41 22 567 89 01',
    uniqueCode: 'CH-TPG-015',
    created: false,
  },
  {
    id: 16,
    text: 'Coop',
    value: 'coop',
    description: 'Service clientèle de Coop.',
    contactEmail: 'clientele@coop.ch',
    phoneNumber: '+41 22 678 90 12',
    uniqueCode: 'CH-COOP-016',
    created: false,
  },
  {
    id: 17,
    text: 'Poste Suisse',
    value: 'poste_suisse',
    description: 'Service postal suisse.',
    contactEmail: 'contact@poste.ch',
    phoneNumber: '+41 22 789 01 23',
    uniqueCode: 'CH-PS-017',
    created: false,
  },
  {
    id: 18,
    text: 'Hôpitaux Universitaires de Genève (HUG)',
    value: 'hopitaux_universitaires_de_geneve',
    description: 'Hôpitaux universitaires offrant des soins médicaux avancés.',
    contactEmail: 'contact@hug.ch',
    phoneNumber: '+41 22 890 12 34',
    uniqueCode: 'CH-HUG-018',
    created: false,
  },
  {
    id: 19,
    text: 'Protection Civile',
    value: 'protection_civile',
    description: "Services de protection civile pour les situations d'urgence.",
    contactEmail: 'protection.civile@city.ch',
    phoneNumber: '+41 22 901 23 45',
    uniqueCode: 'CH-PC-019',
    created: false,
  },
  {
    id: 20,
    text: 'Ambulances Privées de Genève',
    value: 'ambulances_privees_de_geneve',
    description: "Services d'ambulance privée à Genève.",
    contactEmail: 'ambulances.privees@city.ch',
    phoneNumber: '+41 22 012 34 56',
    uniqueCode: 'CH-APG-020',
    created: false,
  },
  {
    id: 21,
    text: 'Service des pompiers',
    value: 'service_des_pompiers',
    description:
      "Service de lutte contre les incendies et interventions d'urgence.",
    contactEmail: 'pompiers@city.ch',
    phoneNumber: '+41 22 123 45 67',
    uniqueCode: 'CH-SDP-021',
    created: false,
  },
  {
    id: 22,
    text: 'Pro Infirmis',
    value: 'pro_infirmis',
    description: 'Organisation offrant des services aux personnes handicapées.',
    contactEmail: 'info@proinfirmis.ch',
    phoneNumber: '+41 22 234 56 78',
    uniqueCode: 'CH-PI-022',
    created: false,
  },
  {
    id: 23,
    text: "Secours d'hiver",
    value: 'secours_d_hiver',
    description: "Organisation d'aide sociale pour les périodes hivernales.",
    contactEmail: 'contact@secoursdhiver.ch',
    phoneNumber: '+41 22 345 67 89',
    uniqueCode: 'CH-SDH-023',
    created: false,
  },
  {
    id: 24,
    text: 'Société de secours mutuels',
    value: 'societe_de_secours_mutuels',
    description: "Organisation d'entraide et de soutien mutuel.",
    contactEmail: 'secours.mutuel@city.ch',
    phoneNumber: '+41 22 456 78 90',
    uniqueCode: 'CH-SSM-024',
    created: false,
  },
  {
    id: 25,
    text: 'Fondation Partage',
    value: 'fondation_partage',
    description:
      'Fondation offrant des services de distribution alimentaire et de soutien social.',
    contactEmail: 'info@fondationpartage.ch',
    phoneNumber: '+41 22 567 89 01',
    uniqueCode: 'CH-FP-025',
    created: false,
  },
  {
    id: 26,
    text: 'signaleur benevole',
    value: 'signaleur_privee',
    description: 'signaleurs benevoles engagée autours de chez sois',
    contactEmail: '',
    phoneNumber: '',
    uniqueCode: 'CH-00-000',
    created: false,
  },
];
