export const signalements = [
  {
    id: '1',
    title: 'Nid de poule dangereux',
    location: 'Rue de la Confédération, Genève',
    date: '15/07/2024 10:30',
    status: 'En cours',
    images: [
      'https://picsum.photos/200/300?random=1',
      'https://picsum.photos/200/300?random=2',
      'https://picsum.photos/200/300?random=3',
    ],
    content:
      'Un nid de poule dangereux a été signalé sur la Rue de la Confédération à Genève.',
    coordinates: {
      lat: 46.2044,
      lng: 6.1432,
    },
    category: 'Infrastructure',
    confirmations: 3,
    resolutionComment: '',
    recipient: ['Service des routes et mobilité, Genève'],
  },
  {
    id: '2',
    title: 'Lampadaire cassé',
    location: 'Avenue de la Paix, Genève',
    date: '14/07/2024 18:45',
    status: 'Résolu',
    images: [
      'https://picsum.photos/200/300?random=4',
      'https://picsum.photos/200/300?random=5',
    ],
    content:
      "Un lampadaire cassé a été signalé sur l'Avenue de la Paix à Genève.",
    coordinates: {
      lat: 46.2267,
      lng: 6.1484,
    },
    category: 'Éclairage public',
    confirmations: 5,
    resolutionComment: 'Le lampadaire a été remplacé par un nouveau.',
    recipient: ["Service de l'éclairage public, Genève"],
  },
  {
    id: '3',
    title: "Fuite d'eau",
    location: 'Boulevard du Théâtre, Genève',
    date: '13/07/2024 12:15',
    status: 'En cours',
    images: ['https://picsum.photos/200/300?random=6'],
    content:
      "Une fuite d'eau a été signalée sur le Boulevard du Théâtre à Genève.",
    coordinates: {
      lat: 46.2074,
      lng: 6.147,
    },
    category: 'Canalisation',
    confirmations: 2,
    resolutionComment: '',
    recipient: ['Service des eaux, Genève'],
  },
  {
    id: '4',
    title: 'Graffiti sur mur',
    location: 'Rue de Carouge, Genève',
    date: '12/07/2024 09:00',
    status: 'Résolu',
    images: [
      'https://picsum.photos/200/300?random=7',
      'https://picsum.photos/200/300?random=8',
      'https://picsum.photos/200/300?random=9',
      'https://picsum.photos/200/300?random=10',
    ],
    content:
      'Des graffitis ont été signalés sur un mur de la Rue de Carouge à Genève.',
    coordinates: {
      lat: 46.1944,
      lng: 6.139,
    },
    category: 'Propreté',
    confirmations: 4,
    resolutionComment:
      'Les graffitis ont été nettoyés par une équipe de nettoyage.',
    recipient: ['Service de la propreté, Genève'],
  },
  {
    id: '5',
    title: 'Arbre tombé',
    location: 'Parc des Bastions, Genève',
    date: '11/07/2024 14:30',
    status: 'En cours',
    images: [
      'https://picsum.photos/200/300?random=11',
      'https://picsum.photos/200/300?random=12',
    ],
    content: 'Un arbre tombé a été signalé au Parc des Bastions à Genève.',
    coordinates: {
      lat: 46.201,
      lng: 6.1457,
    },
    category: 'Végétation',
    confirmations: 3,
    resolutionComment: '',
    recipient: ['Service des espaces verts, Genève'],
  },
  {
    id: '6',
    title: 'Voiture abandonnée',
    location: 'Rue du Mont-Blanc, Genève',
    date: '10/07/2024 16:45',
    status: 'En cours',
    images: [
      'https://picsum.photos/200/300?random=13',
      'https://picsum.photos/200/300?random=14',
      'https://picsum.photos/200/300?random=15',
    ],
    content:
      'Une voiture abandonnée a été signalée sur la Rue du Mont-Blanc à Genève.',
    coordinates: {
      lat: 46.2071,
      lng: 6.1466,
    },
    category: 'Véhicules',
    confirmations: 6,
    resolutionComment: '',
    recipient: ['Police municipale, Genève'],
  },
  {
    id: '7',
    title: 'Déchets encombrants',
    location: 'Rue de Lausanne, Genève',
    date: '09/07/2024 18:20',
    status: 'Résolu',
    images: ['https://picsum.photos/200/300?random=16'],
    content:
      'Des déchets encombrants ont été signalés sur la Rue de Lausanne à Genève.',
    coordinates: {
      lat: 46.21,
      lng: 6.1483,
    },
    category: 'Propreté',
    confirmations: 5,
    resolutionComment:
      'Les déchets ont été enlevés par le service de propreté de la ville.',
    recipient: ['Service de la propreté, Genève'],
  },
  {
    id: '8',
    title: 'Feu de signalisation défectueux',
    location: 'Place du Molard, Genève',
    date: '08/07/2024 07:30',
    status: 'En cours',
    images: [
      'https://picsum.photos/200/300?random=17',
      'https://picsum.photos/200/300?random=18',
    ],
    content:
      'Un feu de signalisation défectueux a été signalé sur la Place du Molard à Genève.',
    coordinates: {
      lat: 46.2045,
      lng: 6.1477,
    },
    category: 'Signalisation',
    confirmations: 7,
    resolutionComment: '',
    recipient: ['Service de la mobilité, Genève'],
  },
  {
    id: '9',
    title: 'Panneau de signalisation manquant',
    location: 'Rue du Rhône, Genève',
    date: '07/07/2024 10:00',
    status: 'Résolu',
    images: [
      'https://picsum.photos/200/300?random=19',
      'https://picsum.photos/200/300?random=20',
      'https://picsum.photos/200/300?random=21',
    ],
    content:
      'Un panneau de signalisation manquant a été signalé sur la Rue du Rhône à Genève.',
    coordinates: {
      lat: 46.2044,
      lng: 6.1505,
    },
    category: 'Signalisation',
    confirmations: 4,
    resolutionComment: 'Le panneau de signalisation a été remplacé.',
    recipient: ['Service de la mobilité, Genève'],
  },
  {
    id: '10',
    title: 'Trottoir endommagé',
    location: "Rue de l'Hôtel-de-Ville, Genève",
    date: '06/07/2024 11:45',
    status: 'En cours',
    images: [
      'https://picsum.photos/200/300?random=22',
      'https://picsum.photos/200/300?random=23',
      'https://picsum.photos/200/300?random=24',
      'https://picsum.photos/200/300?random=25',
      'https://picsum.photos/200/300?random=26',
    ],
    content:
      "Un trottoir endommagé a été signalé sur la Rue de l'Hôtel-de-Ville à Genève.",
    coordinates: {
      lat: 46.2018,
      lng: 6.1481,
    },
    category: 'Infrastructure',
    confirmations: 3,
    resolutionComment: '',
    recipient: ['Service des routes et mobilité, Genève'],
  },
  {
    id: '11',
    title: "Comportement raciste d'un vendeur",
    location: 'Migros Balexert, Genève',
    date: '16/07/2024 14:15',
    status: 'En cours',
    images: [],
    content:
      "Une personne a signalé le comportement raciste d'un vendeur à Migros Balexert à Genève.",
    coordinates: {
      lat: 46.2181,
      lng: 6.1209,
    },
    category: 'Comportement',
    confirmations: 1,
    resolutionComment: '',
    recipient: ['Service clientèle Migros'],
  },
];
